### ISSUE TITLE
Test 1 failing with PostgreSQL 12: ERROR:  could not determine which collation to use for string comparison

### ISSUE THREAD

**Issue by df7cb** [ssinger/slony1-engine#15] opened 2019-06-03 14:37 UTC
Building and running tests against 12beta1, test 1 fails:
```
15:49:09 ############### test1 ###############
15:49:09 Creating new PostgreSQL cluster 12/regress ...
15:49:09 /usr/lib/postgresql/12/bin/initdb -D /var/lib/postgresql/12/regress --auth-local peer --auth-host md5 --username=postgres --pwfile=/tmp/pgpassword.JSQXnG --nosync
15:49:09 The files belonging to this database system will be owned by user "postgres".
15:49:09 This user must also own the server process.
15:49:09 
15:49:09 The database cluster will be initialized with locale "C.UTF-8".
15:49:09 The default database encoding has accordingly been set to "UTF8".
15:49:09 The default text search configuration will be set to "english".
15:49:09 
15:49:09 Data page checksums are disabled.
15:49:09 
15:49:09 fixing permissions on existing directory /var/lib/postgresql/12/regress ... ok
15:49:09 creating subdirectories ... ok
15:49:09 selecting dynamic shared memory implementation ... posix
15:49:09 selecting default max_connections ... 100
15:49:09 selecting default shared_buffers ... 128MB
15:49:09 selecting default timezone ... Etc/UTC
15:49:09 creating configuration files ... ok
15:49:09 running bootstrap script ... ok
15:49:10 performing post-bootstrap initialization ... ok
15:49:10 
15:49:10 Sync to disk skipped.
15:49:10 The data directory might become corrupt if the operating system crashes.
15:49:10 
15:49:10 Success. You can now start the database server using:
15:49:10 
15:49:10     pg_ctlcluster 12 regress start
15:49:10 
15:49:12 Ver Cluster Port Status Owner    Data directory                 Log file
15:49:12 12  regress 5432 online postgres /var/lib/postgresql/12/regress /var/log/postgresql/postgresql-12-regress.log
15:49:12 
15:49:12 test: test1
15:49:12 ----------------------------------------------------
15:49:12 
15:49:12   
15:49:12 test1 is a basic test that replication generally functions.  
15:49:12   
15:49:12 It creates three simple tables as one replication set, and replicates
15:49:12 them from one database to another.
15:49:12   
15:49:12 The tables are of the several interesting types:
15:49:12   
15:49:12 1.  table1 has a formal primary key
15:49:12 
15:49:12 2.  table2 lacks a formal primary key, but has a candidate primary key
15:49:12 
15:49:12 It tries replicating a third table, which has an invalid candidate
15:49:12 primary key (columns not defined NOT NULL), which should cause it to
15:49:12 be rejected.  That is done in a slonik TRY {} block.
15:49:12 
15:49:12 It also creates...
15:49:12 
15:49:12 5.  table4 which has columns of all sorts of vaguely esoteric types to
15:49:12 exercise that points, paths, bitmaps, mac addresses, and inet types
15:49:12 replicate properly.
15:49:12 
15:49:12 5.1  table5 has a composite primary key (on id1,id2,id3) where
15:49:12 the primary key attributes are strewn throughout the table.  This is
15:49:12 to make sure we have a case that exercises the logic that changed with
15:49:12 bug #18.
15:49:12 
15:49:12 6.  It does a test of the function generate_sync_event() to make sure
15:49:12 that it works as expected
15:49:12 
15:49:12 7.  It does a run of UPDATE FUNCTIONS against node 1.  This verifies
15:49:12 that there are at least no syntax errors in the stored function.
15:49:12 
15:49:12 8.  It uses a slon.conf file for node #2 to make sure that the logic
15:49:12 of the config file parser gets exercised.
15:49:12 
15:49:12 9.  It runs the cleanupEvent() function by hand
15:49:12 ----------------------------------------------------
15:49:12 Test by j.random.luser@example.net to be summarized in /tmp/Slony-I-test-results.log
15:49:12 ./run_test.sh: 260: ./run_test.sh: /usr/lib/postgresql/12/bin/createlang: not found
15:49:12 ./run_test.sh: 294: ./run_test.sh: /usr/lib/postgresql/12/bin/createlang: not found
15:49:13 ./run_test.sh: ERROR: Slonik error see /tmp/slony-regress.7BFvxe/slonik.log for details
15:49:13 ./run_test.sh: 219: [: xSlonik: unexpected operator
15:49:13 ERROR:  schema "_Slony_Regress1" does not exist
15:49:13 LINE 1: select "_Slony_Regress1".getModuleversion() || '|' || "_Slon...
15:49:13                ^
15:49:13 
15:49:13 *** /var/log/postgresql/postgresql-12-regress.log (last 100 lines) ***
15:49:13 2019-06-03 13:49:10.484 UTC [16656] LOG:  starting PostgreSQL 12beta1 (Debian 12~beta1-1.pgdg+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-7) 8.3.0, 64-bit
15:49:13 2019-06-03 13:49:10.485 UTC [16656] LOG:  listening on IPv6 address "::1", port 5432
15:49:13 2019-06-03 13:49:10.485 UTC [16656] LOG:  listening on IPv4 address "127.0.0.1", port 5432
15:49:13 2019-06-03 13:49:10.485 UTC [16656] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
15:49:13 2019-06-03 13:49:10.496 UTC [16657] LOG:  database system was shut down at 2019-06-03 13:49:10 UTC
15:49:13 2019-06-03 13:49:10.499 UTC [16656] LOG:  database system is ready to accept connections
15:49:13 2019-06-03 13:49:13.160 UTC [16726] postgres@slonyregress1 ERROR:  could not determine which collation to use for string comparison
15:49:13 2019-06-03 13:49:13.160 UTC [16726] postgres@slonyregress1 HINT:  Use the COLLATE clause to set the collation explicitly.
15:49:13 2019-06-03 13:49:13.160 UTC [16726] postgres@slonyregress1 CONTEXT:  PL/pgSQL function "_Slony_Regress1".enablenode_int(integer) line 47 at assignment
15:49:13 	SQL statement "SELECT "_Slony_Regress1".enableNode_int (p_no_id)"
15:49:13 	PL/pgSQL function "_Slony_Regress1".enablenode(integer) line 30 at PERFORM
15:49:13 2019-06-03 13:49:13.160 UTC [16726] postgres@slonyregress1 STATEMENT:  lock table "_Slony_Regress1".sl_event_lock, "_Slony_Regress1".sl_config_lock;select "_Slony_Regress1".initializeLocalNode(1, 'Regress test node'); select "_Slony_Regress1".enableNode(1); 
15:49:13 2019-06-03 13:49:13.188 UTC [16737] postgres@slonyregress1 ERROR:  schema "_Slony_Regress1" does not exist at character 8
15:49:13 2019-06-03 13:49:13.188 UTC [16737] postgres@slonyregress1 STATEMENT:  select "_Slony_Regress1".getModuleversion() || '|' || "_Slony_Regress1".slonyVersionMajor() || '|' || "_Slony_Regress1".slonyVersionMinor() || '|' || "_Slony_Regress1".slonyVersionPatchlevel() || '|' || version() || '|';
15:49:13 Dropping cluster 12/regress ...
15:49:13 /tmp/slony-regress.7BFvxe/slonik.log:
15:49:13 <stdin>:2: PGRES_FATAL_ERROR lock table "_Slony_Regress1".sl_event_lock, "_Slony_Regress1".sl_config_lock;select "_Slony_Regress1".initializeLocalNode(1, 'Regress test node'); select "_Slony_Regress1".enableNode(1);  - ERROR:  could not determine which collation to use for string comparison
15:49:13 HINT:  Use the COLLATE clause to set the collation explicitly.
15:49:13 CONTEXT:  PL/pgSQL function "_Slony_Regress1".enablenode_int(integer) line 47 at assignment
15:49:13 SQL statement "SELECT "_Slony_Regress1".enableNode_int (p_no_id)"
15:49:13 PL/pgSQL function "_Slony_Regress1".enablenode(integer) line 30 at PERFORM
15:49:13 <stdin>:2: Possible unsupported PostgreSQL version (120000) 12.0, defaulting to 8.4 support
```

A new release would be appreciated so I can update the Debian package. Thanks!

**Comment by ssinger** [comment] 2019-06-16 02:15
#17 probably fixes this but I haven't been able to get it to past the regression tests since slon is causing PG12 to segfault in the analyze.

**Comment by ssinger** [comment] 2019-06-21 02:41
Fixed in commit https://github.com/ssinger/slony1-engine/commit/bb4872b8d2350b3ca4cc13b8b5d8068717412555

**Closed by ssinger** 2019-06-21 02:41 UTC
